#!/usr/bin/env bash
# This script install nginx on a webserver
# And make the return page to be Hello World

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
