#!/usr/bin/env bash
# a script for configuring redirection

sudo apt-get update
sudo apt-get -y install nginx
echo "<p>Hello World</p>" >> /var/www/html/index.html 
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Unique-Usman permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-available/default

sudo service nginx restart
