#!/usr/bin/env bash
# "display the content of /etc/passwd in story format"
# 	using the while loop + IFS.
# 	display the content of /etc/password
while IFS=":" read -r username x userid groupid user_info home_directory command_shell; do
    echo "The user $username is part of the $groupid gang, lives in $home_directory and rides $command_shell. $userid's place is protected by the passcode $x, more info about the user here: $user_info"
done < /etc/passwd
