#!/usr/bin/env bash
# change localhost to 127.0.0.2
# facebook.com 8.8.8.8

sudo cp /etc/hosts ~/hosts.new
sed -i "s\127.0.0.1\127.0.0.2\g" ~/hosts.new
echo -e "8.8.8.8\tfacebook.com" >> ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
