#!/usr/bin/env bash
# A bash script for fizzbuzz

for i in {1..100}
do
	a=""
	if [ $(( i % 3)) -eq 0 ]
	then
		a+="Fizz"
	fi
	if [ $(( i % 5)) -eq 0 ]
	then
		a+="Buzz"
	fi
	if [ $(( i % 5 )) -ne 0 ] && [ $(( i % 3 )) -ne 0 ]
	then
		echo "$i"
	else
		echo "$a"
	fi
done
